### ISSUE TITLE
Allay Todo

### ISSUE THREAD

**Issue by Xfrtrex** [Osmiooo/wildmodplus#1]
- [ ] Allay drops held items on death
- [ ] Better fly goal
- [x] When given item, allay finds more of the item that the player has given.
- [ ] Allays spawn in cages in pillager outposts and in prisons in woodland mansion

**Comment by Xfrtrex** [comment]
im no good at making issues there is way more but idk how to say them, please edit
